// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.pay.domain
/**
 *
 */
class BOAccountRender
    extends com.mogobiz.RenderBase<com.mogobiz.pay.domain.BOAccount>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.pay.domain.BOAccount entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(com.mogobiz.pay.domain.BOAccount entity){return "com.mogobiz.pay.domain.BOAccount : "+entity.id}

}
