// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.geolocation.domain

import com.mogobiz.json.RenderUtil;

/**
 *
 */
class PoiRender
    extends com.mogobiz.geolocation.domain.LocationRender
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.geolocation.domain.Poi entity, String lang = 'fr') {
		return RenderUtil.asMapForJSON(["id",
"latitude", "longitude", "road1", 
"road2", "road3", "roadNum", 
"postalCode", "state", "city", 
"countryCode", "name", "description", "visibility", "picture", "video", "isMain", "pictureType", "externalId", "source", "detail", "maxPrice", "minPrice", "poiType"], entity);
	}

    def String asString(com.mogobiz.geolocation.domain.Poi entity){return "com.mogobiz.geolocation.domain.Poi : "+entity.id}

}
