// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.geolocation.domain

import com.mogobiz.RenderBase

/**
 *
 */
class PoiTypeRender
    extends RenderBase<com.mogobiz.geolocation.domain.PoiType>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.geolocation.domain.PoiType entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(com.mogobiz.geolocation.domain.PoiType entity){return "com.mogobiz.geolocation.domain.PoiType : "+entity.id}

}
