//
//     Generated by: RenderBase.vsl in andromda-grails-cartridge.
package com.mogobiz.service

abstract class RenderBase<T extends Serializable> {
    java.util.Map asMap(T entity) {
        return com.mogobiz.json.RenderUtil.asMapForJSON(entity)
    }
    String asString(T entity) { return entity.toString() }
}