alter table account drop foreign key FKB9D38A2D4BE157D4;
alter table account drop foreign key FKB9D38A2D602DCF9;
alter table account_xrole drop foreign key FKE0E95C5C722BA4BD;
alter table account_xrole drop foreign key FKE0E95C5CD411C165;
alter table album drop foreign key FK5897E6F602DCF9;
alter table b_o_cart drop foreign key FK28764B6D602DCF9;
alter table b_o_cart_item drop foreign key FK6C2D04A583966C6F;
alter table b_o_cart_item_b_o_product drop foreign key FK9CBD90E89ADC15EF;
alter table b_o_cart_item_b_o_product drop foreign key FK9CBD90E8D5BC215E;
alter table b_o_product drop foreign key FK6A96FD8255ECAFB9;
alter table b_o_product_consumption drop foreign key FK7DEB1C5E482BBE0F;
alter table b_o_product_consumption drop foreign key FK7DEB1C5EC732E1A3;
alter table b_o_ticket_type drop foreign key FK929693A0AA1CE819;
alter table brand drop foreign key FK59A4B87388BBDF6;
alter table brand drop foreign key FK59A4B879ECA6F9;
alter table brand drop foreign key FK59A4B87602DCF9;
alter table brand_property drop foreign key FKC8B7CB8DBBA1B1F9;
alter table category drop foreign key FK302BCFE7ACA6B63;
alter table category drop foreign key FK302BCFE9ECA6F9;
alter table category drop foreign key FK302BCFEA332E779;
alter table category drop foreign key FK302BCFE602DCF9;
alter table company drop foreign key FK38A73C7D4BE157D4;
alter table company drop foreign key FK38A73C7D95DE64BC;
alter table company drop foreign key FK38A73C7D66C87106;
alter table company drop foreign key FK38A73C7DE9DA1D86;
alter table company_property drop foreign key FKDBCB8F57602DCF9;
alter table consumption drop foreign key FKCD71F39B3F4326A2;
alter table coupon drop foreign key FKAF42D826B59D3920;
alter table coupon drop foreign key FKAF42D826602DCF9;
alter table coupon_category drop foreign key FK9DBEE0F7E2497A99;
alter table coupon_category drop foreign key FK9DBEE0F75B0C66E5;
alter table coupon_product drop foreign key FK8730C5D69035CA51;
alter table coupon_product drop foreign key FK8730C5D655ECB00F;
alter table coupon_reduction_rule drop foreign key FK3BE2B281169FC5DE;
alter table coupon_reduction_rule drop foreign key FK3BE2B2818AF42876;
alter table coupon_ticket_type drop foreign key FKC1AC11F4504E2EF;
alter table coupon_ticket_type drop foreign key FKC1AC11F42FDE5D9E;
alter table date_period drop foreign key FK4A56237255ECAFB9;
alter table es_env drop foreign key FKB2DABDDC602DCF9;
alter table event drop foreign key FK5C6729A793C84EF;
alter table event drop foreign key FK5C6729A31A24C8F;
alter table event drop foreign key FK5C6729A55ECAFB9;
alter table event_period_sale drop foreign key FK22F2DE055ECAFB9;
alter table external_account drop foreign key FK5A0D99B9793C84EF;
alter table feature drop foreign key FKC5A27AF65B0C668F;
alter table feature drop foreign key FKC5A27AF655ECAFB9;
alter table google_variation_mapping drop foreign key FK60362A1CF0CF6B53;
alter table google_variation_mapping drop foreign key FK60362A1C602DCF9;
alter table google_variation_mapping drop foreign key FK60362A1CFD6CB975;
alter table google_variation_value drop foreign key FKF3469E3FF0CF6B53;
alter table ibeacon drop foreign key FK5F6619ED602DCF9;
alter table intra_day_period drop foreign key FKF581D04555ECAFB9;
alter table location drop foreign key FK714F9FB59319BF09;
alter table poi_type drop foreign key FK1AF5740F49BA7844;
alter table product drop foreign key FKED8DCCEF5B0C668F;
alter table product drop foreign key FKED8DCCEFA797D6B4;
alter table product drop foreign key FKED8DCCEFBBA1B1F9;
alter table product drop foreign key FKED8DCCEFA99249AF;
alter table product drop foreign key FKED8DCCEFF333CFD0;
alter table product drop foreign key FKED8DCCEFBF86FC94;
alter table product drop foreign key FKED8DCCEF9ECA6F9;
alter table product drop foreign key FKED8DCCEF602DCF9;
alter table product drop foreign key FKED8DCCEF1EE8688F;
alter table product2_resource drop foreign key FK8AABBAA31A24C8F;
alter table product2_resource drop foreign key FK8AABBAA55ECAFB9;
alter table product_property drop foreign key FK61FB5F2555ECAFB9;
alter table product_tag drop foreign key FKA71CAC4A912A004F;
alter table product_tag drop foreign key FKA71CAC4A4347CEAF;
alter table role_permission drop foreign key FKBD40D538D411C10F;
alter table role_permission drop foreign key FKBD40D538F3E69A2F;
alter table seller drop foreign key FKC9FF4F7F8201A451;
alter table seller_company drop foreign key FKCC6A43BD602DD4F;
alter table seller_company drop foreign key FKCC6A43BD3E1049D3;
alter table shipping_rule drop foreign key FK2062CEED602DCF9;
alter table stock_calendar drop foreign key FK89EECE472FDE5D48;
alter table stock_calendar drop foreign key FK89EECE4755ECAFB9;
alter table suggestion drop foreign key FK4763CA04BD55124F;
alter table suggestion drop foreign key FK4763CA0455ECAFB9;
alter table tag drop foreign key FK1BF9A9ECA6F9;
alter table tax_rate drop foreign key FKEF7A58F4602DCF9;
alter table tax_rate_local_tax_rate drop foreign key FK859561F3982D71D;
alter table tax_rate_local_tax_rate drop foreign key FK859561F3279E7339;
alter table ticket_type drop foreign key FK158DE48D8AC3CD9F;
alter table ticket_type drop foreign key FK158DE48D6255814E;
alter table ticket_type drop foreign key FK158DE48D6255F5AD;
alter table ticket_type drop foreign key FK158DE48D62550CEF;
alter table ticket_type drop foreign key FK158DE48D55ECAFB9;
alter table token drop foreign key FK696B9F9793C84EF;
alter table user_permission drop foreign key FK30BA72C3793C84EF;
alter table user_permission drop foreign key FK30BA72C3F3E69A2F;
alter table user_property drop foreign key FKC7D137C9793C84EF;
alter table variation drop foreign key FKFB1DA2135B0C668F;
alter table variation_value drop foreign key FKB8BB7C45284D93F9;
alter table xcatalog drop foreign key FKD2AC68A1602DCF9;
alter table xresource drop foreign key FK6BBFCC86A797D6B4;
alter table xresource drop foreign key FK6BBFCC86BF86FC94;
alter table xresource drop foreign key FK6BBFCC86602DCF9;
alter table xresource drop foreign key FK6BBFCC861865E8F9;
drop table if exists account;
drop table if exists account_xrole;
drop table if exists album;
drop table if exists b_o_cart;
drop table if exists b_o_cart_item;
drop table if exists b_o_cart_item_b_o_product;
drop table if exists b_o_product;
drop table if exists b_o_product_consumption;
drop table if exists b_o_ticket_type;
drop table if exists brand;
drop table if exists brand_property;
drop table if exists category;
drop table if exists company;
drop table if exists company_property;
drop table if exists consumption;
drop table if exists coupon;
drop table if exists coupon_category;
drop table if exists coupon_product;
drop table if exists coupon_reduction_rule;
drop table if exists coupon_ticket_type;
drop table if exists date_period;
drop table if exists es_env;
drop table if exists event;
drop table if exists event_period_sale;
drop table if exists external_account;
drop table if exists external_auth_login;
drop table if exists feature;
drop table if exists google_category;
drop table if exists google_content;
drop table if exists google_env;
drop table if exists google_variation_mapping;
drop table if exists google_variation_type;
drop table if exists google_variation_value;
drop table if exists ibeacon;
drop table if exists intra_day_period;
drop table if exists local_tax_rate;
drop table if exists location;
drop table if exists pending_email_confirmation;
drop table if exists permission;
drop table if exists poi_type;
drop table if exists product;
drop table if exists product2_resource;
drop table if exists product_property;
drop table if exists product_tag;
drop table if exists reduction_rule;
drop table if exists reduction_sold;
drop table if exists role_permission;
drop table if exists seller;
drop table if exists seller_company;
drop table if exists shipping;
drop table if exists shipping_carriers;
drop table if exists shipping_rule;
drop table if exists stock;
drop table if exists stock_calendar;
drop table if exists suggestion;
drop table if exists tag;
drop table if exists tax_rate;
drop table if exists tax_rate_local_tax_rate;
drop table if exists ticket_type;
drop table if exists token;
drop table if exists user_permission;
drop table if exists user_property;
drop table if exists uuid_data;
drop table if exists variation;
drop table if exists variation_value;
drop table if exists xcatalog;
drop table if exists xresource;
drop table if exists xrole;
drop table if exists xtranslation;