// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.pay.domain
/**
 *
 */
class BOTransactionValidation
    extends com.mogobiz.ValidationBase<com.mogobiz.pay.domain.BOTransaction>
{

    def beforeInsert(com.mogobiz.pay.domain.BOTransaction entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(com.mogobiz.pay.domain.BOTransaction entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(com.mogobiz.pay.domain.BOTransaction entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(com.mogobiz.pay.domain.BOTransaction entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(com.mogobiz.pay.domain.BOTransaction entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(com.mogobiz.pay.domain.BOTransaction entity) {
        super.afterDelete(entity)
    }

    def onLoad(com.mogobiz.pay.domain.BOTransaction entity) {
        super.onLoad(entity)
    }


}
