// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEnumeration.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;
/**
 * 
 */
enum CivilityType
{
MR("Monsieur"), MRS("Madame"), MISS("Mademoiselle")
    private java.lang.String value
    private CivilityType(java.lang.String value){
        this.value = value
    }

	String getKey(){
		name()
	}

    /**
     * @see java.lang.Object#toString()
     */
    public String toString(){
        return java.lang.String.valueOf(value)
    }
}