/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEntity.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;

import grails.persistence.Entity
import groovy.transform.EqualsAndHashCode

/**
 * 
 */
@Entity
@EqualsAndHashCode(includes="id")
class GoogleCategory
    implements java.io.Serializable
{
    def googleCategoryValidation
    def googleCategoryRender

    java.util.Date dateCreated
    java.util.Date lastUpdated

    String uuid = java.util.UUID.randomUUID().toString()


    /**
     * 
     */
    java.lang.String name 
    /**
     * 
     */
    java.lang.String path 
    /**
     * 
     */
    java.lang.String lang 
    /**
     * 
     */
    java.lang.String parentPath 
    static transients = [ 'googleCategoryValidation', 'googleCategoryRender' ]


    static mapping = {

        autoTimestamp true

    uuid column:"uuid",insertable:true,updateable:false,lazy:false,cache:false


        cache usage:'read-write'

        tablePerHierarchy false

        table 'google_category'

        version false

        id name:'id',column:'id',generator:'native'
        name column:"name",insertable:true,updateable:true,lazy:false,cache:false
        path column:"path",insertable:true,updateable:true,lazy:false,cache:false,length:512
        lang column:"lang",insertable:true,updateable:true,lazy:false,cache:false
        parentPath column:"parent_path",insertable:true,updateable:true,lazy:false,cache:false,length:512

    }

    static constraints = {
    uuid (nullable:false, unique:false)

        name ( blank:false, nullable:false, unique:false)
        path ( blank:false, nullable:false, unique:false)
        lang ( blank:false, nullable:false, unique:false)
        parentPath (nullable:true, unique:false)
    }


    String toString(){return googleCategoryRender?.asString(this)}

    def beforeInsert = {
        googleCategoryValidation.beforeInsert(this)
    }

    def beforeUpdate = {
        googleCategoryValidation.beforeUpdate(this)
    }

    def beforeDelete = {
        googleCategoryValidation.beforeDelete(this)
    }

    def beforeValidate = {
        googleCategoryValidation.beforeValidate(this)
    }

    def afterInsert = {
        googleCategoryValidation.afterInsert(this)
    }

    def afterUpdate = {
        googleCategoryValidation.afterUpdate(this)
    }

    def afterDelete = {
        googleCategoryValidation.afterDelete(this)
    }

    def onLoad = {
        googleCategoryValidation.onLoad(this)
    }

    java.util.Map asMapForJSON(java.util.List<String> included = [], java.util.List<String> excluded = [], String lang = 'fr') {return googleCategoryRender.asMap(included, excluded, this, lang)}

    // GrailsEntity.vsl merge-point
}