// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEntity.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;

import grails.persistence.Entity
import groovy.transform.EqualsAndHashCode

/**
 *
 */
@Entity
@EqualsAndHashCode(includes="id")
class ProfilePermission
    implements java.io.Serializable
{
    def profilePermissionValidation
    def profilePermissionRender

    java.util.Date dateCreated
    java.util.Date lastUpdated

    String uuid = java.util.UUID.randomUUID().toString()


    /**
     *
     */
    java.lang.String target
    /**
     *
     */
    java.lang.String actions  = "*"
    /**
     *
     */
    java.lang.String key
    /**
     *
     */
    com.mogobiz.store.domain.Permission permission

    /**
     *
     */
    com.mogobiz.store.domain.Profile profile

    static transients = [ 'profilePermissionValidation', 'profilePermissionRender' ]

    static belongsTo = [Profile]

    static mapping = {

        autoTimestamp true

    uuid column:"uuid",insertable:true,updateable:false,lazy:false,cache:false



        cache usage:'read-write'

        tablePerHierarchy false

        table 'profile_permission'

        version false

        id name:'id',column:'id',generator:'native'
        target column:"target",insertable:true,updateable:true,lazy:false,cache:false
        actions column:"actions",insertable:true,updateable:true,lazy:false,cache:false
        key column:"xkey",insertable:true,updateable:true,lazy:false,cache:false


        permission column:"permission_fk",insertable:true,updateable:true,lazy:true,cache:'read-write'

        profile column:"profile_fk",insertable:true,updateable:true,lazy:true,cache:'read-write'
    }

    static constraints = {
    uuid (nullable:false, unique:false)

        target ( blank:false, nullable:false, unique:false, validator:com.mogobiz.store.domain.ProfilePermissionValidation.profilePermissionTargetValidator)
        actions ( blank:false, nullable:false, unique:false)
        key (nullable:true, unique:false)
        permission ( blank:false, nullable:false)
        profile ( blank:false, nullable:false)
    }


    String toString(){return profilePermissionRender?.asString(this)}

    def beforeInsert = {
        profilePermissionValidation.beforeInsert(this)
    }

    def beforeUpdate = {
        profilePermissionValidation.beforeUpdate(this)
    }

    def beforeDelete = {
        profilePermissionValidation.beforeDelete(this)
    }

    def beforeValidate = {
        profilePermissionValidation.beforeValidate(this)
    }

    def afterInsert = {
        profilePermissionValidation.afterInsert(this)
    }

    def afterUpdate = {
        profilePermissionValidation.afterUpdate(this)
    }

    def afterDelete = {
        profilePermissionValidation.afterDelete(this)
    }

    def onLoad = {
        profilePermissionValidation.onLoad(this)
    }

    java.util.Map asMapForJSON(java.util.List<String> included = [], java.util.List<String> excluded = [], String lang = 'fr') {return profilePermissionRender.asMap(included, excluded, this, lang)}

    // GrailsEntity.vsl merge-point
}
