// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEntity.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;

import grails.persistence.Entity
import groovy.transform.EqualsAndHashCode

/**
 * 
 */
@Entity
@EqualsAndHashCode(includes="id")
class ReductionSold
    implements java.io.Serializable
{
    def reductionSoldValidation
    def reductionSoldRender

    java.util.Date dateCreated
    java.util.Date lastUpdated

    String uuid = java.util.UUID.randomUUID().toString()


    /**
     * 
     */
    long sold 
    static transients = [ 'reductionSoldValidation', 'reductionSoldRender' ]


    static mapping = {

        autoTimestamp true

    uuid column:"uuid",insertable:true,updateable:false,lazy:false,cache:false


        cache usage:'read-write'

        tablePerHierarchy false

        table 'reduction_sold'

        version false

        id name:'id',column:'id',generator:'native'
        sold column:"sold",insertable:true,updateable:true,lazy:false,cache:false

    }

    static constraints = {
    uuid (nullable:false, unique:false)

        sold ( blank:false, nullable:false, unique:false)
    }


    String toString(){return reductionSoldRender.asString(this)}

    def beforeInsert = {
        reductionSoldValidation.beforeInsert(this)
    }

    def beforeUpdate = {
        reductionSoldValidation.beforeUpdate(this)
    }

    def beforeDelete = {
        reductionSoldValidation.beforeDelete(this)
    }

    def beforeValidate = {
        reductionSoldValidation.beforeValidate(this)
    }

    def afterInsert = {
        reductionSoldValidation.afterInsert(this)
    }

    def afterUpdate = {
        reductionSoldValidation.afterUpdate(this)
    }

    def afterDelete = {
        reductionSoldValidation.afterDelete(this)
    }

    def onLoad = {
        reductionSoldValidation.onLoad(this)
    }

    java.util.Map asMapForJSON(java.util.List<String> included = [], java.util.List<String> excluded = [], String lang = 'fr') {return reductionSoldRender.asMap(included, excluded, this, lang)}

    // GrailsEntity.vsl merge-point
}