// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEntity.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;

import grails.persistence.Entity
import groovy.transform.EqualsAndHashCode

/**
 * 
 */
@Entity
@EqualsAndHashCode(includes="id")
class Role
    implements java.io.Serializable
{
    def roleValidation
    def roleRender

    java.util.Date dateCreated
    java.util.Date lastUpdated

    String uuid = java.util.UUID.randomUUID().toString()


    /**
     * 
     */
    com.mogobiz.store.domain.RoleName name 
    static transients = [ 'roleValidation', 'roleRender' ]


    static mapping = {

        autoTimestamp true

    uuid column:"uuid",insertable:true,updateable:false,lazy:false,cache:false


        cache usage:'read-write'

        tablePerHierarchy false

        table 'role'

        version false

        id name:'id',column:'id',generator:'native'
        name column:"name",enumType:"string",insertable:true,updateable:true,lazy:false,cache:false

    }

    static constraints = {
    uuid (nullable:false, unique:false)

        name ( blank:false, nullable:false, unique:true)
    }

    static com.mogobiz.store.domain.Role findByName(final com.mogobiz.store.domain.RoleName name)
    {
        return Role.findByName("from com.mogobiz.store.domain.Role as role where role.name = :name", name);
    }

    static com.mogobiz.store.domain.Role findByName(final java.lang.String queryString, final com.mogobiz.store.domain.RoleName name)
    {
        def ret = Role.executeQuery(queryString, [name:name]).iterator()
        return ret.hasNext()?ret.next():null
    }

    String toString(){return roleRender.asString(this)}

    def beforeInsert = {
        roleValidation.beforeInsert(this)
    }

    def beforeUpdate = {
        roleValidation.beforeUpdate(this)
    }

    def beforeDelete = {
        roleValidation.beforeDelete(this)
    }

    def beforeValidate = {
        roleValidation.beforeValidate(this)
    }

    def afterInsert = {
        roleValidation.afterInsert(this)
    }

    def afterUpdate = {
        roleValidation.afterUpdate(this)
    }

    def afterDelete = {
        roleValidation.afterDelete(this)
    }

    def onLoad = {
        roleValidation.onLoad(this)
    }

    java.util.Map asMapForJSON(java.util.List<String> included = [], java.util.List<String> excluded = [], String lang = 'fr') {return roleRender.asMap(included, excluded, this, lang)}

    // GrailsEntity.vsl merge-point
}