/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: GrailsEntity.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain;
/**
 * 
 */
class Stock implements java.io.Serializable
{
// If super inheritance is 'interface', render super properties etc
// render the properties and associations (if any)

    /**
     * <p>
     * Negative value means unlimited
     * </p>
     */
    java.lang.Long stock 
    /**
     * 
     */
    boolean stockUnlimited  = true 
    /**
     * 
     */
    boolean stockOutSelling  = false // END Entity 




    static mapping = {

        autoTimestamp true

    uuid column:"uuid",insertable:true,updateable:false,lazy:false,cache:false



        cache true

        version false




    }

    static constraints = {
        stock (nullable:true, unique:false)
        stockUnlimited ( blank:false, nullable:false, unique:false)
        stockOutSelling ( blank:false, nullable:false, unique:false)
    }

    // GrailsEntity.vsl merge-point
}