/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * 
 */
public class CartVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -9096448257155148152L;

    public CartVO()
    {
        this.price = 0;
        this.reduction = 0;
        this.finalPrice = 0;
        this.count = 0;
    }

    public CartVO(long price, long reduction, long finalPrice, int count)
    {
        this.price = price;
        this.reduction = reduction;
        this.finalPrice = finalPrice;
        this.count = count;
    }

    public CartVO(long price, java.lang.Long endPrice, long reduction, long finalPrice, int count, java.lang.String uuid, com.mogobiz.store.vo.CartItemVO[] cartItemVOs, com.mogobiz.store.vo.CouponVO[] coupons)
    {
        this.price = price;
        this.endPrice = endPrice;
        this.reduction = reduction;
        this.finalPrice = finalPrice;
        this.count = count;
        this.uuid = uuid;
        this.cartItemVOs = cartItemVOs;
        this.coupons = coupons;
    }

    /**
     * Copies constructor from other CartVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public CartVO(CartVO otherBean)
    {
        this(otherBean.getPrice(), otherBean.getEndPrice(), otherBean.getReduction(), otherBean.getFinalPrice(), otherBean.getCount(), otherBean.getUuid(), otherBean.getCartItemVOs(), otherBean.getCoupons());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(CartVO otherBean)
    {
        if (otherBean != null)
        {
            this.setPrice(otherBean.getPrice());
            this.setEndPrice(otherBean.getEndPrice());
            this.setReduction(otherBean.getReduction());
            this.setFinalPrice(otherBean.getFinalPrice());
            this.setCount(otherBean.getCount());
            this.setUuid(otherBean.getUuid());
            this.setCartItemVOs(otherBean.getCartItemVOs());
            this.setCoupons(otherBean.getCoupons());
        }
    }

    private long price;

    /**
     * 
     */
    public long getPrice()
    {
        return this.price;
    }

    public void setPrice(long price)
    {
        this.price = price;
    }

    private java.lang.Long endPrice;

    /**
     * 
     */
    public java.lang.Long getEndPrice()
    {
        return this.endPrice;
    }

    public void setEndPrice(java.lang.Long endPrice)
    {
        this.endPrice = endPrice;
    }

    private long reduction;

    /**
     * 
     */
    public long getReduction()
    {
        return this.reduction;
    }

    public void setReduction(long reduction)
    {
        this.reduction = reduction;
    }

    private long finalPrice;

    /**
     * 
     */
    public long getFinalPrice()
    {
        return this.finalPrice;
    }

    public void setFinalPrice(long finalPrice)
    {
        this.finalPrice = finalPrice;
    }

    private int count;

    /**
     * 
     */
    public int getCount()
    {
        return this.count;
    }

    public void setCount(int count)
    {
        this.count = count;
    }

    private java.lang.String uuid;

    /**
     * <p>
     * The uuid of the tempory BOCart when the cart was prepared before
     * payment.
     * </p>
     */
    public java.lang.String getUuid()
    {
        return this.uuid;
    }

    public void setUuid(java.lang.String uuid)
    {
        this.uuid = uuid;
    }

    private com.mogobiz.store.vo.CartItemVO[] cartItemVOs;

    /**
     * Get the cartItemVOs
     * 
     */
    public com.mogobiz.store.vo.CartItemVO[] getCartItemVOs()
    {
        return this.cartItemVOs;
    }

    /**
     * Sets the cartItemVOs
     */
    public void setCartItemVOs(com.mogobiz.store.vo.CartItemVO[] cartItemVOs)
    {
        this.cartItemVOs = cartItemVOs;
    }

    private com.mogobiz.store.vo.CouponVO[] coupons;

    /**
     * Get the coupons
     * 
     */
    public com.mogobiz.store.vo.CouponVO[] getCoupons()
    {
        return this.coupons;
    }

    /**
     * Sets the coupons
     */
    public void setCoupons(com.mogobiz.store.vo.CouponVO[] coupons)
    {
        this.coupons = coupons;
    }

}