/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * 
 */
public class CartItemVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -8945302843309210180L;

    public CartItemVO()
    {
        this.id = null;
        this.productId = 0;
        this.productName = null;
        this.xtype = null;
        this.calendarType = null;
        this.skuName = null;
        this.quantity = 0;
        this.price = 0;
        this.tax = null;
        this.totalPrice = 0;
        this.registeredCartItemVOs = null;
    }

    public CartItemVO(java.lang.String id, long productId, java.lang.String productName, com.mogobiz.store.domain.ProductType xtype, com.mogobiz.store.domain.ProductCalendar calendarType, java.lang.String skuName, int quantity, long price, java.lang.Float tax, long totalPrice, com.mogobiz.store.vo.RegisteredCartItemVO[] registeredCartItemVOs)
    {
        this.id = id;
        this.productId = productId;
        this.productName = productName;
        this.xtype = xtype;
        this.calendarType = calendarType;
        this.skuName = skuName;
        this.quantity = quantity;
        this.price = price;
        this.tax = tax;
        this.totalPrice = totalPrice;
        this.registeredCartItemVOs = registeredCartItemVOs;
    }

    public CartItemVO(java.lang.String id, long productId, java.lang.String productName, com.mogobiz.store.domain.ProductType xtype, com.mogobiz.store.domain.ProductCalendar calendarType, java.lang.Long skuId, java.lang.String skuName, int quantity, long price, java.lang.Long endPrice, java.lang.Float tax, long totalPrice, java.lang.Long totalEndPrice, java.util.Calendar startDate, java.util.Calendar endDate, com.mogobiz.store.vo.RegisteredCartItemVO[] registeredCartItemVOs, com.mogobiz.store.vo.ShippingVO shipping)
    {
        this.id = id;
        this.productId = productId;
        this.productName = productName;
        this.xtype = xtype;
        this.calendarType = calendarType;
        this.skuId = skuId;
        this.skuName = skuName;
        this.quantity = quantity;
        this.price = price;
        this.endPrice = endPrice;
        this.tax = tax;
        this.totalPrice = totalPrice;
        this.totalEndPrice = totalEndPrice;
        this.startDate = startDate;
        this.endDate = endDate;
        this.registeredCartItemVOs = registeredCartItemVOs;
        this.shipping = shipping;
    }

    /**
     * Copies constructor from other CartItemVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public CartItemVO(CartItemVO otherBean)
    {
        this(otherBean.getId(), otherBean.getProductId(), otherBean.getProductName(), otherBean.getXtype(), otherBean.getCalendarType(), otherBean.getSkuId(), otherBean.getSkuName(), otherBean.getQuantity(), otherBean.getPrice(), otherBean.getEndPrice(), otherBean.getTax(), otherBean.getTotalPrice(), otherBean.getTotalEndPrice(), otherBean.getStartDate(), otherBean.getEndDate(), otherBean.getRegisteredCartItemVOs(), otherBean.getShipping());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(CartItemVO otherBean)
    {
        if (otherBean != null)
        {
            this.setId(otherBean.getId());
            this.setProductId(otherBean.getProductId());
            this.setProductName(otherBean.getProductName());
            this.setXtype(otherBean.getXtype());
            this.setCalendarType(otherBean.getCalendarType());
            this.setSkuId(otherBean.getSkuId());
            this.setSkuName(otherBean.getSkuName());
            this.setQuantity(otherBean.getQuantity());
            this.setPrice(otherBean.getPrice());
            this.setEndPrice(otherBean.getEndPrice());
            this.setTax(otherBean.getTax());
            this.setTotalPrice(otherBean.getTotalPrice());
            this.setTotalEndPrice(otherBean.getTotalEndPrice());
            this.setStartDate(otherBean.getStartDate());
            this.setEndDate(otherBean.getEndDate());
            this.setRegisteredCartItemVOs(otherBean.getRegisteredCartItemVOs());
            this.setShipping(otherBean.getShipping());
        }
    }

    private java.lang.String id;

    /**
     * <p>
     * Id de la session du panier qui contient l'item
     * </p>
     */
    public java.lang.String getId()
    {
        return this.id;
    }

    public void setId(java.lang.String id)
    {
        this.id = id;
    }

    private long productId;

    /**
     * <p>
     * Id du produit
     * </p>
     */
    public long getProductId()
    {
        return this.productId;
    }

    public void setProductId(long productId)
    {
        this.productId = productId;
    }

    private java.lang.String productName;

    /**
     * <p>
     * Id du produit
     * </p>
     */
    public java.lang.String getProductName()
    {
        return this.productName;
    }

    public void setProductName(java.lang.String productName)
    {
        this.productName = productName;
    }

    private com.mogobiz.store.domain.ProductType xtype;

    /**
     * <p>
     * Nom du SKU du produit
     * </p>
     */
    public com.mogobiz.store.domain.ProductType getXtype()
    {
        return this.xtype;
    }

    public void setXtype(com.mogobiz.store.domain.ProductType xtype)
    {
        this.xtype = xtype;
    }

    private com.mogobiz.store.domain.ProductCalendar calendarType;

    /**
     * 
     */
    public com.mogobiz.store.domain.ProductCalendar getCalendarType()
    {
        return this.calendarType;
    }

    public void setCalendarType(com.mogobiz.store.domain.ProductCalendar calendarType)
    {
        this.calendarType = calendarType;
    }

    private java.lang.Long skuId;

    /**
     * <p>
     * Id du SKU du produit
     * </p>
     */
    public java.lang.Long getSkuId()
    {
        return this.skuId;
    }

    public void setSkuId(java.lang.Long skuId)
    {
        this.skuId = skuId;
    }

    private java.lang.String skuName;

    /**
     * <p>
     * Nom du SKU du produit
     * </p>
     */
    public java.lang.String getSkuName()
    {
        return this.skuName;
    }

    public void setSkuName(java.lang.String skuName)
    {
        this.skuName = skuName;
    }

    private int quantity = 1;

    /**
     * <p>
     * Quantité désirée (pour le SKU du produit)
     * </p>
     */
    public int getQuantity()
    {
        return this.quantity;
    }

    public void setQuantity(int quantity)
    {
        this.quantity = quantity;
    }

    private long price;

    /**
     * <p>
     * Prix unitaire du SKU
     * </p>
     */
    public long getPrice()
    {
        return this.price;
    }

    public void setPrice(long price)
    {
        this.price = price;
    }

    private java.lang.Long endPrice;

    /**
     * <p>
     * Prix unitaire du SKU
     * </p>
     */
    public java.lang.Long getEndPrice()
    {
        return this.endPrice;
    }

    public void setEndPrice(java.lang.Long endPrice)
    {
        this.endPrice = endPrice;
    }

    private java.lang.Float tax;

    /**
     * <p>
     * Prix unitaire du SKU
     * </p>
     */
    public java.lang.Float getTax()
    {
        return this.tax;
    }

    public void setTax(java.lang.Float tax)
    {
        this.tax = tax;
    }

    private long totalPrice;

    /**
     * <p>
     * Prix unitaire du SKU
     * </p>
     */
    public long getTotalPrice()
    {
        return this.totalPrice;
    }

    public void setTotalPrice(long totalPrice)
    {
        this.totalPrice = totalPrice;
    }

    private java.lang.Long totalEndPrice;

    /**
     * <p>
     * Prix unitaire du SKU
     * </p>
     */
    public java.lang.Long getTotalEndPrice()
    {
        return this.totalEndPrice;
    }

    public void setTotalEndPrice(java.lang.Long totalEndPrice)
    {
        this.totalEndPrice = totalEndPrice;
    }

    private java.util.Calendar startDate;

    /**
     * <p>
     * Date d'utilisation du SKU
     * </p>
     */
    public java.util.Calendar getStartDate()
    {
        return this.startDate;
    }

    public void setStartDate(java.util.Calendar startDate)
    {
        this.startDate = startDate;
    }

    private java.util.Calendar endDate;

    /**
     * <p>
     * Date d'utilisation du SKU
     * </p>
     */
    public java.util.Calendar getEndDate()
    {
        return this.endDate;
    }

    public void setEndDate(java.util.Calendar endDate)
    {
        this.endDate = endDate;
    }

    private com.mogobiz.store.vo.RegisteredCartItemVO[] registeredCartItemVOs;

    /**
     * Get the registeredCartItemVOs
     * 
     */
    public com.mogobiz.store.vo.RegisteredCartItemVO[] getRegisteredCartItemVOs()
    {
        return this.registeredCartItemVOs;
    }

    /**
     * Sets the registeredCartItemVOs
     */
    public void setRegisteredCartItemVOs(com.mogobiz.store.vo.RegisteredCartItemVO[] registeredCartItemVOs)
    {
        this.registeredCartItemVOs = registeredCartItemVOs;
    }

    private com.mogobiz.store.vo.ShippingVO shipping;

    /**
     * Get the shipping
     * 
     */
    public com.mogobiz.store.vo.ShippingVO getShipping()
    {
        return this.shipping;
    }

    /**
     * Sets the shipping
     */
    public void setShipping(com.mogobiz.store.vo.ShippingVO shipping)
    {
        this.shipping = shipping;
    }

}