/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * <p>
 * Informations correspondant aux bon de réductions saisis par le
 * client. Le client saisi uniquement le code, le reste des
 * informations est mis à jour à chaque restitution du panier
 * (notamment l'indicateur active, les dates et le prix)
 * </p>
 */
public class CouponVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1205858241710040686L;

    public CouponVO()
    {
        this.id = 0;
        this.name = null;
        this.code = null;
        this.active = false;
        this.price = 0;
    }

    public CouponVO(long id, java.lang.String name, java.lang.String code, boolean active, long price)
    {
        this.id = id;
        this.name = name;
        this.code = code;
        this.active = active;
        this.price = price;
    }

    public CouponVO(long id, java.lang.String name, java.lang.String code, boolean active, java.util.Calendar startDate, java.util.Calendar endDate, long price, java.lang.String pastille, java.lang.String description)
    {
        this.id = id;
        this.name = name;
        this.code = code;
        this.active = active;
        this.startDate = startDate;
        this.endDate = endDate;
        this.price = price;
        this.pastille = pastille;
        this.description = description;
    }

    /**
     * Copies constructor from other CouponVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public CouponVO(CouponVO otherBean)
    {
        this(otherBean.getId(), otherBean.getName(), otherBean.getCode(), otherBean.isActive(), otherBean.getStartDate(), otherBean.getEndDate(), otherBean.getPrice(), otherBean.getPastille(), otherBean.getDescription());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(CouponVO otherBean)
    {
        if (otherBean != null)
        {
            this.setId(otherBean.getId());
            this.setName(otherBean.getName());
            this.setCode(otherBean.getCode());
            this.setActive(otherBean.isActive());
            this.setStartDate(otherBean.getStartDate());
            this.setEndDate(otherBean.getEndDate());
            this.setPrice(otherBean.getPrice());
            this.setPastille(otherBean.getPastille());
            this.setDescription(otherBean.getDescription());
        }
    }

    private long id;

    /**
     * 
     */
    public long getId()
    {
        return this.id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private java.lang.String code;

    /**
     * 
     */
    public java.lang.String getCode()
    {
        return this.code;
    }

    public void setCode(java.lang.String code)
    {
        this.code = code;
    }

    private boolean active = true;

    /**
     * 
     */
    public boolean isActive()
    {
        return this.active;
    }

    public void setActive(boolean active)
    {
        this.active = active;
    }

    private java.util.Calendar startDate;

    /**
     * 
     */
    public java.util.Calendar getStartDate()
    {
        return this.startDate;
    }

    public void setStartDate(java.util.Calendar startDate)
    {
        this.startDate = startDate;
    }

    private java.util.Calendar endDate;

    /**
     * 
     */
    public java.util.Calendar getEndDate()
    {
        return this.endDate;
    }

    public void setEndDate(java.util.Calendar endDate)
    {
        this.endDate = endDate;
    }

    private long price;

    /**
     * 
     */
    public long getPrice()
    {
        return this.price;
    }

    public void setPrice(long price)
    {
        this.price = price;
    }

    private java.lang.String pastille;

    /**
     * 
     */
    public java.lang.String getPastille()
    {
        return this.pastille;
    }

    public void setPastille(java.lang.String pastille)
    {
        this.pastille = pastille;
    }

    private java.lang.String description;

    /**
     * 
     */
    public java.lang.String getDescription()
    {
        return this.description;
    }

    public void setDescription(java.lang.String description)
    {
        this.description = description;
    }

}