/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * <p>
 * Element nominatif d'un article du panier.
 * </p>
 */
public class RegisteredCartItemVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5789028598300935042L;

    public RegisteredCartItemVO()
    {
        this.cartItemId = null;
        this.id = null;
        this.email = null;
    }

    public RegisteredCartItemVO(java.lang.String cartItemId, java.lang.String id, java.lang.String email)
    {
        this.cartItemId = cartItemId;
        this.id = id;
        this.email = email;
    }

    public RegisteredCartItemVO(java.lang.String cartItemId, java.lang.String id, java.lang.String email, java.lang.String firstname, java.lang.String lastname, java.lang.String phone, java.util.Calendar birthdate)
    {
        this.cartItemId = cartItemId;
        this.id = id;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.phone = phone;
        this.birthdate = birthdate;
    }

    /**
     * Copies constructor from other RegisteredCartItemVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public RegisteredCartItemVO(RegisteredCartItemVO otherBean)
    {
        this(otherBean.getCartItemId(), otherBean.getId(), otherBean.getEmail(), otherBean.getFirstname(), otherBean.getLastname(), otherBean.getPhone(), otherBean.getBirthdate());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(RegisteredCartItemVO otherBean)
    {
        if (otherBean != null)
        {
            this.setCartItemId(otherBean.getCartItemId());
            this.setId(otherBean.getId());
            this.setEmail(otherBean.getEmail());
            this.setFirstname(otherBean.getFirstname());
            this.setLastname(otherBean.getLastname());
            this.setPhone(otherBean.getPhone());
            this.setBirthdate(otherBean.getBirthdate());
        }
    }

    private java.lang.String cartItemId;

    /**
     * <p>
     * Id de la session du panier qui contient l'item
     * </p>
     */
    public java.lang.String getCartItemId()
    {
        return this.cartItemId;
    }

    public void setCartItemId(java.lang.String cartItemId)
    {
        this.cartItemId = cartItemId;
    }

    private java.lang.String id;

    /**
     * <p>
     * Id de la session du panier qui contient l'item
     * </p>
     */
    public java.lang.String getId()
    {
        return this.id;
    }

    public void setId(java.lang.String id)
    {
        this.id = id;
    }

    private java.lang.String email;

    /**
     * 
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    private java.lang.String firstname;

    /**
     * 
     */
    public java.lang.String getFirstname()
    {
        return this.firstname;
    }

    public void setFirstname(java.lang.String firstname)
    {
        this.firstname = firstname;
    }

    private java.lang.String lastname;

    /**
     * 
     */
    public java.lang.String getLastname()
    {
        return this.lastname;
    }

    public void setLastname(java.lang.String lastname)
    {
        this.lastname = lastname;
    }

    private java.lang.String phone;

    /**
     * 
     */
    public java.lang.String getPhone()
    {
        return this.phone;
    }

    public void setPhone(java.lang.String phone)
    {
        this.phone = phone;
    }

    private java.util.Calendar birthdate;

    /**
     * 
     */
    public java.util.Calendar getBirthdate()
    {
        return this.birthdate;
    }

    public void setBirthdate(java.util.Calendar birthdate)
    {
        this.birthdate = birthdate;
    }

}