/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * 
 */
public class ShippingVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6406389438647470021L;

    public ShippingVO()
    {
        this.weight = 0;
        this.weightUnit = null;
        this.width = 0;
        this.height = 0;
        this.depth = null;
        this.linearUnit = null;
        this.amount = 0;
        this.free = false;
    }

    public ShippingVO(long weight, com.mogobiz.store.domain.WeightUnit weightUnit, long width, long height, java.lang.Long depth, com.mogobiz.store.domain.LinearUnit linearUnit, long amount, boolean free)
    {
        this.weight = weight;
        this.weightUnit = weightUnit;
        this.width = width;
        this.height = height;
        this.depth = depth;
        this.linearUnit = linearUnit;
        this.amount = amount;
        this.free = free;
    }

    /**
     * Copies constructor from other ShippingVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public ShippingVO(ShippingVO otherBean)
    {
        this(otherBean.getWeight(), otherBean.getWeightUnit(), otherBean.getWidth(), otherBean.getHeight(), otherBean.getDepth(), otherBean.getLinearUnit(), otherBean.getAmount(), otherBean.isFree());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(ShippingVO otherBean)
    {
        if (otherBean != null)
        {
            this.setWeight(otherBean.getWeight());
            this.setWeightUnit(otherBean.getWeightUnit());
            this.setWidth(otherBean.getWidth());
            this.setHeight(otherBean.getHeight());
            this.setDepth(otherBean.getDepth());
            this.setLinearUnit(otherBean.getLinearUnit());
            this.setAmount(otherBean.getAmount());
            this.setFree(otherBean.isFree());
        }
    }

    private long weight;

    /**
     * 
     */
    public long getWeight()
    {
        return this.weight;
    }

    public void setWeight(long weight)
    {
        this.weight = weight;
    }

    private com.mogobiz.store.domain.WeightUnit weightUnit;

    /**
     * 
     */
    public com.mogobiz.store.domain.WeightUnit getWeightUnit()
    {
        return this.weightUnit;
    }

    public void setWeightUnit(com.mogobiz.store.domain.WeightUnit weightUnit)
    {
        this.weightUnit = weightUnit;
    }

    private long width;

    /**
     * 
     */
    public long getWidth()
    {
        return this.width;
    }

    public void setWidth(long width)
    {
        this.width = width;
    }

    private long height;

    /**
     * 
     */
    public long getHeight()
    {
        return this.height;
    }

    public void setHeight(long height)
    {
        this.height = height;
    }

    private java.lang.Long depth;

    /**
     * 
     */
    public java.lang.Long getDepth()
    {
        return this.depth;
    }

    public void setDepth(java.lang.Long depth)
    {
        this.depth = depth;
    }

    private com.mogobiz.store.domain.LinearUnit linearUnit;

    /**
     * 
     */
    public com.mogobiz.store.domain.LinearUnit getLinearUnit()
    {
        return this.linearUnit;
    }

    public void setLinearUnit(com.mogobiz.store.domain.LinearUnit linearUnit)
    {
        this.linearUnit = linearUnit;
    }

    private long amount;

    /**
     * 
     */
    public long getAmount()
    {
        return this.amount;
    }

    public void setAmount(long amount)
    {
        this.amount = amount;
    }

    private boolean free = false;

    /**
     * 
     */
    public boolean isFree()
    {
        return this.free;
    }

    public void setFree(boolean free)
    {
        this.free = free;
    }

}