/*
 * Copyright (C) 2015 Mogobiz SARL. All rights reserved.
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mogobiz.store.vo;

/**
 * 
 */
public class TicketTypeVO
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6075118449978428752L;

    public TicketTypeVO()
    {
        this.name = null;
        this.minOrder = 0;
        this.maxOrder = 0;
        this.amount = 0;
    }

    public TicketTypeVO(java.lang.String name, int minOrder, int maxOrder, float amount)
    {
        this.name = name;
        this.minOrder = minOrder;
        this.maxOrder = maxOrder;
        this.amount = amount;
    }

    /**
     * Copies constructor from other TicketTypeVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public TicketTypeVO(TicketTypeVO otherBean)
    {
        this(otherBean.getName(), otherBean.getMinOrder(), otherBean.getMaxOrder(), otherBean.getAmount());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(TicketTypeVO otherBean)
    {
        if (otherBean != null)
        {
            this.setName(otherBean.getName());
            this.setMinOrder(otherBean.getMinOrder());
            this.setMaxOrder(otherBean.getMaxOrder());
            this.setAmount(otherBean.getAmount());
        }
    }

    private java.lang.String name;

    /**
     * 
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    public void setName(java.lang.String name)
    {
        this.name = name;
    }

    private int minOrder = -1;

    /**
     * 
     */
    public int getMinOrder()
    {
        return this.minOrder;
    }

    public void setMinOrder(int minOrder)
    {
        this.minOrder = minOrder;
    }

    private int maxOrder = -1;

    /**
     * 
     */
    public int getMaxOrder()
    {
        return this.maxOrder;
    }

    public void setMaxOrder(int maxOrder)
    {
        this.maxOrder = maxOrder;
    }

    private float amount;

    /**
     * 
     */
    public float getAmount()
    {
        return this.amount;
    }

    public void setAmount(float amount)
    {
        this.amount = amount;
    }

}