//
//     Generated by: ValidationBase.vsl in andromda-grails-cartridge.
package com.mogobiz.service

class ValidationBase<T  extends Serializable> {
    def beforeInsert(T entity) {
        // your implementation goes here
    }

    def beforeUpdate(T entity) {
        // your implementation goes here
    }

    def beforeDelete(T entity) {
        // your implementation goes here
    }

    def beforeValidate(T entity) {
        // your implementation goes here
    }

    def afterInsert(T entity) {
        // your implementation goes here
    }

    def afterUpdate(T entity) {
        // your implementation goes here
    }

    def afterDelete(T entity) {
        // your implementation goes here
    }

    def onLoad(T entity) {
        // your implementation goes here
    }

}