// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.geolocation.domain

import com.mogobiz.ValidationBase

/**
 *
 */
class LocationValidation
    extends ValidationBase<com.mogobiz.geolocation.domain.Location>
{

    def beforeInsert(com.mogobiz.geolocation.domain.Location entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(com.mogobiz.geolocation.domain.Location entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(com.mogobiz.geolocation.domain.Location entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(com.mogobiz.geolocation.domain.Location entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(com.mogobiz.geolocation.domain.Location entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(com.mogobiz.geolocation.domain.Location entity) {
        super.afterDelete(entity)
    }

    def onLoad(com.mogobiz.geolocation.domain.Location entity) {
        super.onLoad(entity)
    }


}
