create table account (id int8 not null, account_type varchar(255), active bool not null, autosign bool not null, birthdate timestamp, civility varchar(255), company_fk int8, date_created timestamp not null, email varchar(255) not null unique, external_id varchar(255), first_name varchar(255), last_name varchar(255), last_updated timestamp not null, location_fk int8, login varchar(255) not null unique, password varchar(255) not null, phone varchar(255), token varchar(255), token_secret varchar(255), uuid varchar(255) not null, primary key (id));
create table account_xrole (roles_fk int8, role_id int8);
create table album (id int8 not null, company_fk int8, date_created timestamp not null, description varchar(255), last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table b_o_cart (id int8 not null, buyer varchar(255) not null, company_fk int8 not null, currency_code varchar(255) not null, currency_rate float8 not null, xdate timestamp not null, date_created timestamp not null, last_updated timestamp not null, price int8 not null, status varchar(255) not null, transaction_uuid varchar(255) unique, uuid varchar(255) not null, primary key (id));
create table b_o_cart_item (id int8 not null, b_o_cart_fk int8 not null, code varchar(255) not null unique, date_created timestamp not null, end_date timestamp, end_price int8 not null, hidden bool not null, last_updated timestamp not null, price int8 not null, quantity int4 not null, start_date timestamp, tax float4 not null, ticket_type_fk int8 not null, total_end_price int8 not null, total_price int8 not null, uuid varchar(255) not null, primary key (id));
create table b_o_cart_item_b_o_product (b_o_products_fk int8, boproduct_id int8);
create table b_o_product (id int8 not null, acquittement bool not null, date_created timestamp not null, last_updated timestamp not null, price int8 not null, principal bool not null, product_fk int8, uuid varchar(255) not null, primary key (id));
create table b_o_product_consumption (consumptions_fk int8, consumption_id int8);
create table b_o_ticket_type (id int8 not null, age int4 not null, b_o_product_fk int8 not null, birthdate timestamp, date_created timestamp not null, email varchar(255), end_date timestamp, firstname varchar(255), last_updated timestamp not null, lastname varchar(255), phone varchar(255), price int8 not null, qrcode text, qrcode_content text, quantity int4 not null, short_code varchar(255), start_date timestamp, ticket_type varchar(255), uuid varchar(255) not null, primary key (id));
create table brand (id int8 not null, company_fk int8 not null, date_created timestamp not null, description text, facebooksite varchar(255), hide bool not null, ibeacon_fk int8, last_updated timestamp not null, name varchar(255) not null, parent_fk int8, twitter varchar(255), uuid varchar(255) not null, website varchar(255), primary key (id));
create table brand_property (id int8 not null, brand_fk int8 not null, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, value varchar(255), primary key (id));
create table category (id int8 not null, catalog_fk int8, company_fk int8 not null, date_created timestamp not null, deleted bool not null, description text, external_code varchar(255), google_category varchar(255), hide bool not null, ibeacon_fk int8, keywords varchar(255), last_updated timestamp not null, name varchar(255) not null, parent_fk int8, position int4 not null, sanitized_name varchar(255), uuid varchar(255) not null, primary key (id));
create table company (id int8 not null, aes_password varchar(255) not null, api_key varchar(255), code varchar(255) not null, country_code varchar(255), currency_code varchar(255), date_created timestamp not null, default_language varchar(255) not null, email varchar(255), external_code varchar(255), gakey varchar(255), google_content_fk int8, google_env_fk int8, handling_time int4, last_updated timestamp not null, location_fk int8, map_provider varchar(255), name varchar(255) not null, online_validation bool not null, phone varchar(255), refund_policy varchar(255), return_policy int4, ship_from_fk int8, shipping_carriers_fedex bool, shipping_carriers_ups bool, shipping_international bool not null, start_date timestamp, stop_date timestamp, temp_session_id varchar(255), uuid varchar(255) not null, website varchar(255), weight_unit varchar(255), primary key (id));
create table company_property (id int8 not null, company_fk int8 not null, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, value varchar(255) not null, primary key (id));
create table consumption (id int8 not null, b_o_ticket_type_fk int8, xdate timestamp not null, date_created timestamp not null, last_updated timestamp not null, uuid varchar(255) not null, primary key (id));
create table coupon (id int8 not null, active bool not null, anonymous bool not null, catalog_wise bool not null, code varchar(255) not null unique, company_fk int8 not null, date_created timestamp not null, description text, end_date timestamp, for_sale bool not null, last_updated timestamp not null, name varchar(255) not null, number_of_uses int8, reduction_sold_fk int8, start_date timestamp, uuid varchar(255) not null, primary key (id));
create table coupon_category (categories_fk int8, category_id int8);
create table coupon_product (products_fk int8, product_id int8);
create table coupon_reduction_rule (rules_fk int8, reduction_rule_id int8);
create table coupon_ticket_type (ticket_types_fk int8, ticket_type_id int8);
create table date_period (id int8 not null, date_created timestamp not null, end_date timestamp not null, last_updated timestamp not null, product_fk int8, start_date timestamp not null, uuid varchar(255) not null, primary key (id));
create table es_env (id int8 not null, active bool not null, company_fk int8 not null, cron_expr varchar(255) not null, date_created timestamp not null, extra text, idx varchar(255), last_updated timestamp not null, name varchar(255) not null, running bool not null, url varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table event (id int8 not null, xdate timestamp not null, date_created timestamp not null, description text, last_updated timestamp not null, product_fk int8, resource_fk int8, user_fk int8 not null, uuid varchar(255) not null, xtype varchar(255) not null, primary key (id));
create table event_period_sale (id int8 not null, date_created timestamp not null, event_date timestamp, event_start_time timestamp, last_updated timestamp not null, nb_ticket_sold int8 not null, product_fk int8, uuid varchar(255) not null, primary key (id));
create table external_account (id int8 not null, account_type varchar(255) not null, date_created timestamp not null, external_id varchar(255), last_updated timestamp not null, login varchar(255) not null, token varchar(255), token_secret varchar(255), user_fk int8 not null, uuid varchar(255) not null, primary key (id));
create table external_auth_login (id int8 not null, account_type varchar(255) not null, birth_date varchar(255), city varchar(255), country varchar(255), date_created timestamp not null, email varchar(255), external_id varchar(255), first_name varchar(255), gender varchar(255), instant timestamp, last_name varchar(255), last_updated timestamp not null, login varchar(255) not null, mobile varchar(255), postal_code varchar(255), road1 varchar(255), road2 varchar(255), road3 varchar(255), road4 varchar(255), token varchar(255), token_secret varchar(255), uuid varchar(255) not null, primary key (id));
create table feature (id int8 not null, category_fk int8, date_created timestamp not null, domain varchar(255), external_code varchar(255), hide bool not null, last_updated timestamp not null, name varchar(255) not null, position int4 not null, product_fk int8, uuid varchar(255) not null, value varchar(255), primary key (id));
create table google_category (id int8 not null, date_created timestamp not null, lang varchar(255) not null, last_updated timestamp not null, name varchar(255) not null, parent_path varchar(512), path varchar(512) not null, uuid varchar(255) not null, primary key (id));
create table google_content (id int8 not null, account_id varchar(255) not null, account_login varchar(255) not null, account_password varchar(255) not null, account_type varchar(255) not null, date_created timestamp not null, google_search bool not null, last_updated timestamp not null, uuid varchar(255) not null, primary key (id));
create table google_env (id int8 not null, active bool not null, client_id varchar(255), client_secret varchar(255), client_token varchar(255), cron_expr varchar(255) not null, date_created timestamp not null, dry_run bool not null, extra text, last_updated timestamp not null, merchant_id varchar(255) not null, merchant_url varchar(255), running bool not null, uuid varchar(255) not null, primary key (id));
create table google_variation_mapping (id int8 not null, company_fk int8 not null, date_created timestamp not null, last_updated timestamp not null, mappings varchar(255) not null, type_fk int8, uuid varchar(255) not null, value_fk int8, primary key (id));
create table google_variation_type (id int8 not null, date_created timestamp not null, last_updated timestamp not null, uuid varchar(255) not null, xtype varchar(255) not null unique, primary key (id));
create table google_variation_value (id int8 not null, date_created timestamp not null, last_updated timestamp not null, type_fk int8 not null, uuid varchar(255) not null, value varchar(255) not null unique, primary key (id));
create table ibeacon (id int8 not null, active bool not null, company_fk int8 not null, date_created timestamp not null, end_date timestamp not null, last_updated timestamp not null, major varchar(255) not null, minor varchar(255) not null, name varchar(255) not null, start_date timestamp not null, uuid varchar(255) not null, primary key (id));
create table intra_day_period (id int8 not null, date_created timestamp not null, end_date timestamp, last_updated timestamp not null, product_fk int8, start_date timestamp, uuid varchar(255) not null, weekday1 bool not null, weekday2 bool not null, weekday3 bool not null, weekday4 bool not null, weekday5 bool not null, weekday6 bool not null, weekday7 bool not null, primary key (id));
create table local_tax_rate (id int8 not null, active bool not null, country_code varchar(255), date_created timestamp not null, last_updated timestamp not null, rate float4 not null, state_code varchar(255), uuid varchar(255) not null, primary key (id));
create table location (id int8 not null, city varchar(255), country_code varchar(255) not null, date_created timestamp not null, last_updated timestamp not null, latitude float8, longitude float8, postal_code varchar(255), road1 varchar(255), road2 varchar(255), road3 varchar(255), road_num varchar(255), state varchar(255), uuid varchar(255) not null, class varchar(255) not null, description varchar(255), detail text, external_id varchar(255), is_main bool, max_price float4, min_price float4, name varchar(255), picture varchar(255), picture_type varchar(255), poi_type_fk int8, source varchar(255), video varchar(255), visibility varchar(255), primary key (id));
create table pending_email_confirmation (id int8 not null, version int8 not null, confirmation_event varchar(80), confirmation_token varchar(80) not null unique, email_address varchar(80) not null, timestamp timestamp not null, user_token varchar(500), primary key (id));
create table permission (id int8 not null, date_created timestamp not null, last_updated timestamp not null, possible_actions varchar(255) not null, type varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table poi_type (id int8 not null, code varchar(255) not null, date_created timestamp not null, icon_fk int8, last_updated timestamp not null, uuid varchar(255) not null, xtype varchar(255) not null unique, primary key (id));
create table product (id int8 not null, availability_date timestamp, brand_fk int8, calendar_type varchar(255), category_fk int8 not null, code varchar(255) not null, company_fk int8 not null, creation_fk int8, date_created timestamp not null, deleted bool not null, description text, description_as_text text, external_code varchar(255), hide bool not null, ibeacon_fk int8, keywords varchar(255), last_updated timestamp not null, modification_date timestamp, name varchar(255) not null, nb_sales int8 not null, picture varchar(255), poi_fk int8, price int8 not null, sanitized_name varchar(255) not null, seller_fk int8, shipping_fk int8, start_date timestamp, start_feature_date timestamp, state varchar(255), stock_display bool, stop_date timestamp, stop_feature_date timestamp, tax_rate_fk int8, uuid varchar(255) not null, xtype varchar(255) not null, primary key (id));
create table product2_resource (id int8 not null, date_created timestamp not null, last_updated timestamp not null, position int4 not null, product_fk int8 not null, resource_fk int8 not null, uuid varchar(255) not null, primary key (id));
create table product_property (id int8 not null, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, product_fk int8 not null, uuid varchar(255) not null, value varchar(255), primary key (id));
create table product_tag (tags_fk int8, tag_id int8);
create table reduction_rule (id int8 not null, date_created timestamp not null, discount varchar(255), last_updated timestamp not null, quantity_max int8, quantity_min int8, uuid varchar(255) not null, x_purchased int8, xtype varchar(255) not null, y_offered int8, primary key (id));
create table reduction_sold (id int8 not null, date_created timestamp not null, last_updated timestamp not null, sold int8 not null, uuid varchar(255) not null, primary key (id));
create table role_permission (id int8 not null, actions varchar(255) not null, date_created timestamp not null, last_updated timestamp not null, permission_fk int8 not null, role_fk int8 not null, target varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table seller (id int8 not null, admin bool not null, agent bool not null, sell bool not null, validator bool not null, primary key (id));
create table seller_company (companies_fk int8, company_id int8);
create table shipping (id int8 not null, amount int8 not null, date_created timestamp not null, depth int8 not null, free bool not null, height int8 not null, last_updated timestamp not null, linear_unit varchar(255) not null, uuid varchar(255) not null, weight int8 not null, weight_unit varchar(255) not null, width int8 not null, primary key (id));
create table shipping_carriers (id int8 not null, fedex bool not null, ups bool not null, primary key (id));
create table shipping_rule (id int8 not null, company_fk int8, country_code varchar(255) not null, date_created timestamp not null, last_updated timestamp not null, max_amount int8 not null, min_amount int8 not null, price varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table stock (id int8 not null, stock int8, stock_out_selling bool not null, stock_unlimited bool not null, primary key (id));
create table stock_calendar (id int8 not null, date_created timestamp not null, last_updated timestamp not null, product_fk int8 not null, sold int8 not null, start_date timestamp, stock int8 not null, ticket_type_fk int8 not null, uuid varchar(255) not null, primary key (id));
create table suggestion (id int8 not null, date_created timestamp not null, discount varchar(255), last_updated timestamp not null, pack_fk int8 not null, position int4 not null, product_fk int8 not null, required bool not null, uuid varchar(255) not null, primary key (id));
create table tag (id int8 not null, date_created timestamp not null, ibeacon_fk int8, last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table tax_rate (id int8 not null, company_fk int8, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table tax_rate_local_tax_rate (local_tax_rates_fk int8, local_tax_rate_id int8);
create table ticket_type (id int8 not null, availability_date timestamp, date_created timestamp not null, description text, external_code varchar(255), gtin varchar(255), last_updated timestamp not null, max_order int4 not null, min_order int4 not null, mpn varchar(255), name varchar(255) not null, nb_sales int8 not null, picture_fk int8, position int4, price int8 not null, product_fk int8 not null, sku varchar(255) not null, start_date timestamp, stock_stock int8, stock_stock_out_selling bool, stock_stock_unlimited bool, stop_date timestamp, uuid varchar(255) not null, variation1_fk int8, variation2_fk int8, variation3_fk int8, xprivate bool, primary key (id));
create table token (id int8 not null, client_id varchar(255) not null, date_created timestamp not null, expires_in int4 not null, last_updated timestamp not null, redirect_u_r_i varchar(255) not null, scope varchar(255), state varchar(255), user_fk int8 not null, uuid varchar(255) not null, value varchar(255) not null, primary key (id));
create table user_permission (id int8 not null, actions varchar(255) not null, date_created timestamp not null, last_updated timestamp not null, permission_fk int8 not null, target varchar(255) not null, user_fk int8 not null, uuid varchar(255) not null, primary key (id));
create table user_property (id int8 not null, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, user_fk int8 not null, uuid varchar(255) not null, value varchar(255), primary key (id));
create table uuid_data (id int8 not null, date_created timestamp not null, expire_date timestamp not null, last_updated timestamp not null, payload text, uuid varchar(255) not null, xtype varchar(255) not null, primary key (id));
create table variation (id int8 not null, category_fk int8, date_created timestamp not null, external_code varchar(255), google_variation_type varchar(255), hide bool not null, last_updated timestamp not null, name varchar(255) not null, position int4 not null, uuid varchar(255) not null, primary key (id));
create table variation_value (id int8 not null, date_created timestamp not null, external_code varchar(255), google_variation_value varchar(255), last_updated timestamp not null, position int4 not null, uuid varchar(255) not null, value varchar(255) not null, variation_fk int8 not null, primary key (id));
create table xcatalog (id int8 not null, activation_date timestamp not null, channels varchar(255), company_fk int8 not null, date_created timestamp not null, deleted bool not null, description text, external_code varchar(255), last_updated timestamp not null, name varchar(255) not null, social bool not null, uuid varchar(255) not null, primary key (id));
create table xresource (id int8 not null, account_type varchar(255), active bool not null, album_fk int8, code varchar(255), company_fk int8, content text, content_type varchar(255), creation_fk int8, date_created timestamp not null, deleted bool not null, description text, external_code varchar(255), last_updated timestamp not null, name varchar(255), poi_fk int8, sanitized_name varchar(255) not null, small_picture varchar(255), uploaded bool not null, url varchar(255), uuid varchar(255) not null, xtype varchar(255) not null, primary key (id));
create table xrole (id int8 not null, date_created timestamp not null, last_updated timestamp not null, name varchar(255) not null, uuid varchar(255) not null, primary key (id));
create table xtranslation (id int8 not null, company_id int8 not null, date_created timestamp not null, lang varchar(255) not null, last_updated timestamp not null, target int8 not null, type varchar(255), uuid varchar(255) not null, value text not null, primary key (id));
alter table account add constraint FKB9D38A2D4BE157D4 foreign key (location_fk) references location;
alter table account add constraint FKB9D38A2D602DCF9 foreign key (company_fk) references company;
alter table account_xrole add constraint FKE0E95C5C722BA4BD foreign key (roles_fk) references account;
alter table account_xrole add constraint FKE0E95C5CD411C165 foreign key (role_id) references xrole;
alter table album add constraint FK5897E6F602DCF9 foreign key (company_fk) references company;
alter table b_o_cart add constraint FK28764B6D602DCF9 foreign key (company_fk) references company;
alter table b_o_cart_item add constraint FK6C2D04A583966C6F foreign key (b_o_cart_fk) references b_o_cart;
alter table b_o_cart_item_b_o_product add constraint FK9CBD90E89ADC15EF foreign key (boproduct_id) references b_o_product;
alter table b_o_cart_item_b_o_product add constraint FK9CBD90E8D5BC215E foreign key (b_o_products_fk) references b_o_cart_item;
alter table b_o_product add constraint FK6A96FD8255ECAFB9 foreign key (product_fk) references product;
alter table b_o_product_consumption add constraint FK7DEB1C5E482BBE0F foreign key (consumption_id) references consumption;
alter table b_o_product_consumption add constraint FK7DEB1C5EC732E1A3 foreign key (consumptions_fk) references b_o_product;
alter table b_o_ticket_type add constraint FK929693A0AA1CE819 foreign key (b_o_product_fk) references b_o_product;
alter table brand add constraint FK59A4B87388BBDF6 foreign key (parent_fk) references brand;
alter table brand add constraint FK59A4B879ECA6F9 foreign key (ibeacon_fk) references ibeacon;
alter table brand add constraint FK59A4B87602DCF9 foreign key (company_fk) references company;
alter table brand_property add constraint FKC8B7CB8DBBA1B1F9 foreign key (brand_fk) references brand;
alter table category add constraint FK302BCFE7ACA6B63 foreign key (parent_fk) references category;
alter table category add constraint FK302BCFE9ECA6F9 foreign key (ibeacon_fk) references ibeacon;
alter table category add constraint FK302BCFEA332E779 foreign key (catalog_fk) references xcatalog;
alter table category add constraint FK302BCFE602DCF9 foreign key (company_fk) references company;
alter table company add constraint FK38A73C7D4BE157D4 foreign key (location_fk) references location;
alter table company add constraint FK38A73C7D95DE64BC foreign key (ship_from_fk) references location;
alter table company add constraint FK38A73C7D66C87106 foreign key (google_content_fk) references google_content;
alter table company add constraint FK38A73C7DE9DA1D86 foreign key (google_env_fk) references google_env;
alter table company_property add constraint FKDBCB8F57602DCF9 foreign key (company_fk) references company;
alter table consumption add constraint FKCD71F39B3F4326A2 foreign key (b_o_ticket_type_fk) references b_o_ticket_type;
alter table coupon add constraint FKAF42D826B59D3920 foreign key (reduction_sold_fk) references reduction_sold;
alter table coupon add constraint FKAF42D826602DCF9 foreign key (company_fk) references company;
alter table coupon_category add constraint FK9DBEE0F7E2497A99 foreign key (categories_fk) references coupon;
alter table coupon_category add constraint FK9DBEE0F75B0C66E5 foreign key (category_id) references category;
alter table coupon_product add constraint FK8730C5D69035CA51 foreign key (products_fk) references coupon;
alter table coupon_product add constraint FK8730C5D655ECB00F foreign key (product_id) references product;
alter table coupon_reduction_rule add constraint FK3BE2B281169FC5DE foreign key (rules_fk) references coupon;
alter table coupon_reduction_rule add constraint FK3BE2B2818AF42876 foreign key (reduction_rule_id) references reduction_rule;
alter table coupon_ticket_type add constraint FKC1AC11F4504E2EF foreign key (ticket_types_fk) references coupon;
alter table coupon_ticket_type add constraint FKC1AC11F42FDE5D9E foreign key (ticket_type_id) references ticket_type;
alter table date_period add constraint FK4A56237255ECAFB9 foreign key (product_fk) references product;
alter table es_env add constraint FKB2DABDDC602DCF9 foreign key (company_fk) references company;
alter table event add constraint FK5C6729A793C84EF foreign key (user_fk) references account;
alter table event add constraint FK5C6729A31A24C8F foreign key (resource_fk) references xresource;
alter table event add constraint FK5C6729A55ECAFB9 foreign key (product_fk) references product;
alter table event_period_sale add constraint FK22F2DE055ECAFB9 foreign key (product_fk) references product;
alter table external_account add constraint FK5A0D99B9793C84EF foreign key (user_fk) references account;
alter table feature add constraint FKC5A27AF65B0C668F foreign key (category_fk) references category;
alter table feature add constraint FKC5A27AF655ECAFB9 foreign key (product_fk) references product;
alter table google_variation_mapping add constraint FK60362A1CF0CF6B53 foreign key (type_fk) references google_variation_type;
alter table google_variation_mapping add constraint FK60362A1C602DCF9 foreign key (company_fk) references company;
alter table google_variation_mapping add constraint FK60362A1CFD6CB975 foreign key (value_fk) references google_variation_value;
alter table google_variation_value add constraint FKF3469E3FF0CF6B53 foreign key (type_fk) references google_variation_type;
alter table ibeacon add constraint FK5F6619ED602DCF9 foreign key (company_fk) references company;
alter table intra_day_period add constraint FKF581D04555ECAFB9 foreign key (product_fk) references product;
alter table location add constraint FK714F9FB59319BF09 foreign key (poi_type_fk) references poi_type;
create index emailconf_timestamp_Idx on pending_email_confirmation (timestamp);
create index emailconf_token_Idx on pending_email_confirmation (confirmation_token);
alter table poi_type add constraint FK1AF5740F49BA7844 foreign key (icon_fk) references xresource;
alter table product add constraint FKED8DCCEF5B0C668F foreign key (category_fk) references category;
alter table product add constraint FKED8DCCEFA797D6B4 foreign key (creation_fk) references event;
alter table product add constraint FKED8DCCEFBBA1B1F9 foreign key (brand_fk) references brand;
alter table product add constraint FKED8DCCEFA99249AF foreign key (seller_fk) references seller;
alter table product add constraint FKED8DCCEFF333CFD0 foreign key (tax_rate_fk) references tax_rate;
alter table product add constraint FKED8DCCEFBF86FC94 foreign key (poi_fk) references location;
alter table product add constraint FKED8DCCEF9ECA6F9 foreign key (ibeacon_fk) references ibeacon;
alter table product add constraint FKED8DCCEF602DCF9 foreign key (company_fk) references company;
alter table product add constraint FKED8DCCEF1EE8688F foreign key (shipping_fk) references shipping;
alter table product2_resource add constraint FK8AABBAA31A24C8F foreign key (resource_fk) references xresource;
alter table product2_resource add constraint FK8AABBAA55ECAFB9 foreign key (product_fk) references product;
alter table product_property add constraint FK61FB5F2555ECAFB9 foreign key (product_fk) references product;
alter table product_tag add constraint FKA71CAC4A912A004F foreign key (tags_fk) references product;
alter table product_tag add constraint FKA71CAC4A4347CEAF foreign key (tag_id) references tag;
alter table role_permission add constraint FKBD40D538D411C10F foreign key (role_fk) references xrole;
alter table role_permission add constraint FKBD40D538F3E69A2F foreign key (permission_fk) references permission;
alter table seller add constraint FKC9FF4F7F8201A451 foreign key (id) references account;
alter table seller_company add constraint FKCC6A43BD602DD4F foreign key (company_id) references company;
alter table seller_company add constraint FKCC6A43BD3E1049D3 foreign key (companies_fk) references seller;
alter table shipping_rule add constraint FK2062CEED602DCF9 foreign key (company_fk) references company;
alter table stock_calendar add constraint FK89EECE472FDE5D48 foreign key (ticket_type_fk) references ticket_type;
alter table stock_calendar add constraint FK89EECE4755ECAFB9 foreign key (product_fk) references product;
alter table suggestion add constraint FK4763CA04BD55124F foreign key (pack_fk) references product;
alter table suggestion add constraint FK4763CA0455ECAFB9 foreign key (product_fk) references product;
alter table tag add constraint FK1BF9A9ECA6F9 foreign key (ibeacon_fk) references ibeacon;
alter table tax_rate add constraint FKEF7A58F4602DCF9 foreign key (company_fk) references company;
alter table tax_rate_local_tax_rate add constraint FK859561F3982D71D foreign key (local_tax_rate_id) references local_tax_rate;
alter table tax_rate_local_tax_rate add constraint FK859561F3279E7339 foreign key (local_tax_rates_fk) references tax_rate;
alter table ticket_type add constraint FK158DE48D8AC3CD9F foreign key (picture_fk) references xresource;
alter table ticket_type add constraint FK158DE48D6255814E foreign key (variation2_fk) references variation_value;
alter table ticket_type add constraint FK158DE48D6255F5AD foreign key (variation3_fk) references variation_value;
alter table ticket_type add constraint FK158DE48D62550CEF foreign key (variation1_fk) references variation_value;
alter table ticket_type add constraint FK158DE48D55ECAFB9 foreign key (product_fk) references product;
alter table token add constraint FK696B9F9793C84EF foreign key (user_fk) references account;
alter table user_permission add constraint FK30BA72C3793C84EF foreign key (user_fk) references account;
alter table user_permission add constraint FK30BA72C3F3E69A2F foreign key (permission_fk) references permission;
alter table user_property add constraint FKC7D137C9793C84EF foreign key (user_fk) references account;
alter table variation add constraint FKFB1DA2135B0C668F foreign key (category_fk) references category;
alter table variation_value add constraint FKB8BB7C45284D93F9 foreign key (variation_fk) references variation;
alter table xcatalog add constraint FKD2AC68A1602DCF9 foreign key (company_fk) references company;
alter table xresource add constraint FK6BBFCC86A797D6B4 foreign key (creation_fk) references event;
alter table xresource add constraint FK6BBFCC86BF86FC94 foreign key (poi_fk) references location;
alter table xresource add constraint FK6BBFCC86602DCF9 foreign key (company_fk) references company;
alter table xresource add constraint FK6BBFCC861865E8F9 foreign key (album_fk) references album;
create sequence hibernate_sequence;