// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class BOCartItemRender
    extends RenderBase<BOCartItem>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.BOCartItem entity, String lang = 'fr') {
        if (included == null || included.size() == 0) {
            included = ["id", "code", "tax", "startDate", "endDate", "quantity"]
        }
        String currencyCode = entity.bOCart.currencyCode
        double currencyRate = entity.bOCart.currencyRate
        Map r = super.asMap(included, excluded, entity, lang)
        r["price"] = formatAmount(entity.price * currencyRate, currencyCode, lang)
        r["endPrice"] = formatAmount(entity.endPrice * currencyRate, currencyCode, lang)
        r["totalPrice"] = formatAmount(entity.totalPrice * currencyRate, currencyCode, lang)
        r["totalEndPrice"] = formatAmount(entity.totalEndPrice * currencyRate, currencyCode, lang)
        if (entity.bOProducts) {
            for (BOProduct boProduct : entity.bOProducts) {
                if (boProduct.principal) {
                    r["name"] = boProduct.product.name
                }
            }
        }
        return r
    }

    def String asString(com.mogobiz.store.domain.BOCartItem entity){return "com.mogobiz.store.domain.BOCartItem : "+entity.id}

}
