// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain
/**
 *
 */
class BoReturnedItemRender
    extends com.mogobiz.RenderBase<com.mogobiz.store.domain.BoReturnedItem>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.BoReturnedItem entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(com.mogobiz.store.domain.BoReturnedItem entity){return "com.mogobiz.store.domain.BoReturnedItem : "+entity.id}

}
