// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain
/**
 *
 */
class BOReturnRender
    extends com.mogobiz.RenderBase<com.mogobiz.store.domain.BOReturn>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.BOReturn entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(com.mogobiz.store.domain.BOReturn entity){return "com.mogobiz.store.domain.BOReturn : "+entity.id}

}
