// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.ValidationBase

/**
 *
 */
class BOTicketTypeValidation
    extends ValidationBase<BOTicketType>
{

    def beforeInsert(com.mogobiz.store.domain.BOTicketType entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(com.mogobiz.store.domain.BOTicketType entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(com.mogobiz.store.domain.BOTicketType entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(com.mogobiz.store.domain.BOTicketType entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(com.mogobiz.store.domain.BOTicketType entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(com.mogobiz.store.domain.BOTicketType entity) {
        super.afterDelete(entity)
    }

    def onLoad(com.mogobiz.store.domain.BOTicketType entity) {
        super.onLoad(entity)
    }


}
