// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class CompanyRender
        extends RenderBase<Company> {

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Company entity, String lang = 'fr') {
        if (included == null || included.size() == 0) {
            included = [
                    'id',
                    'externalCode',
                    'code',
                    // begin general
                    'name',
                    'website',
                    'phone',
                    'email',
                    'aboutUs',
                    'termsAndPolicies',
                    // location
                    'location',
                    'location.id',
                    'location.city',
                    'location.road1',
                    'location.road2',
                    'location.road3',
                    'location.roadNum',
                    'location.postalCode',
                    'location.countryCode',
                    'location.state',
                    // end general
                    // begin shipping policy
                    // shipping address from
                    'shipFrom',
                    'shipFrom.id',
                    'shipFrom.city',
                    'shipFrom.road1',
                    'shipFrom.road2',
                    'shipFrom.postalCode',
                    'shipFrom.countryCode',
                    'shipFrom.state',
                    // shipping carriers
                    'shippingCarriers',
                    'shippingCarriers.ups',
                    'shippingCarriers.fedex',
                    // international shipping
                    'shippingInternational',
                    // handling time
                    'handlingTime',
                    // weight unit
                    'weightUnit',
                    // refund policy
                    'refundPolicy',
                    // return policy
                    'returnPolicy',
                    // end shipping policy
                    // begin payment policy
                    'currencyCode',
                    'calendarType',
                    // payment policy
                    'gakey',
                    'orderNotificationURL',
                    'orderNotificationEmail',
                    'apiKey',
                    'onlineValidation',
                    'mapProvider'
                    // end payment policy
            ]
        }
        Map result = super.asMap(included, excluded, entity, lang);
        translate(result, entity, lang)
        return result;
    }

    def String asString(com.mogobiz.store.domain.Company entity) {
        return "com.mogobiz.store.domain.Company : " + entity.id
    }

}
