// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class EsEnvRender
    extends RenderBase<EsEnv>
{

    java.util.Map asMap(com.mogobiz.store.domain.EsEnv entity) {return super.asMap(entity)}

    def String asString(com.mogobiz.store.domain.EsEnv entity){return "com.mogobiz.store.domain.EsEnv : "+entity.id}

}
