// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class EsEnvRender
    extends RenderBase<EsEnv>
{

    Map asMap(EsEnv entity) {
        return super.asMap([
            'id',
            'name',
            'url',
            'idx',
            'active',
            'cronExpr',
            'running',
            'success',
            'extra',
            'company',
            'company.id'
        ], [], entity)
    }

    def String asString(EsEnv entity){return "com.mogobiz.store.domain.EsEnv : "+entity.id}

}
