// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class GoogleEnvRender
    extends RenderBase<GoogleEnv>
{

    Map asMap(List<String> included = [], List<String> excluded = [], GoogleEnv entity, String lang = 'fr') {
        return super.asMap(included, excluded, entity, lang)
    }

    def String asString(GoogleEnv entity){
        return "com.mogobiz.store.domain.GoogleEnv : "+entity.id
    }

}
