// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class IntraDayPeriodRender
    extends RenderBase<IntraDayPeriod>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.IntraDayPeriod entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = ['id',
				'startDate',
				'endDate',
				'product',
				'product.id',
				'weekday1',
				'weekday2',
				'weekday3',
				'weekday4',
				'weekday5',
				'weekday6',
				'weekday7'
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		translate(result, entity, lang)
		return result;
	}

    def String asString(com.mogobiz.store.domain.IntraDayPeriod entity){return "com.mogobiz.store.domain.IntraDayPeriod : "+entity.id}

}
