// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.json.RenderUtil
import com.mogobiz.RenderBase;

/**
 *
 */
class Product2ResourceRender
    extends RenderBase<Product2Resource>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Product2Resource entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = [
				'id',
				'position',
				'montant',
				'resource',
				'resource.id',
				'resource.name',
				'resource.code',
				'resource.active',
				'resource.deleted',
				'resource.description',
				'resource.xtype',
				'resource.content',
				'resource.uploaded',
				'resource.url',
				'resource.smallPicture',
				'resource.poi',
				'resource.poi.id',
				'resource.creation',
				'resource.creation.date',
				'resource.creation.user',
				'resource.creation.user.firstName',
				'resource.creation.user.lastName',
				'resource.creation.user.email'
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		result['resource']['url'] = RenderUtil.extractResourceUrl(entity.resource)
		result['resource']['smallPicture'] = RenderUtil.extractResourceSmallPicture(entity.resource)
		translate(result, entity, lang)
		return result;
	}

    def String asString(com.mogobiz.store.domain.Product2Resource entity){return "com.mogobiz.store.domain.Product2Resource : "+entity.id}

}
