// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase
import com.mogobiz.json.RenderUtil

/**
 *
 */
class ResourceRender
    extends RenderBase<Resource>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Resource entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = [
				'id',
				'name',
				'code',
				'active',
				'deleted',
				'description',
				'xtype',
				'content',
				'uploaded',
				'poi',
				'poi.id',
				'creation',
				'creation.date',
				'creation.user',
				'creation.user.firstName',
				'creation.user.lastName',
				'creation.user.email',
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		result['url'] = RenderUtil.extractResourceUrl(entity)
		result['smallPicture'] = RenderUtil.extractResourceSmallPicture(entity)

		return result
	}

    def String asString(com.mogobiz.store.domain.Resource entity){return "com.mogobiz.store.domain.Resource : "+entity.id}

}
