// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase
import com.mogobiz.utils.ProfileUtils

/**
 *
 */
class RolePermissionRender extends RenderBase<RolePermission>
{

    Map asMap(List<String> included = [], List<String> excluded = [], RolePermission entity, String lang = 'fr') {
        def map = super.asMap(included && !included.isEmpty() ? included : ['id', 'role', 'role.id', 'target'], excluded, entity, lang)
        map << [key: entity.key ?: ProfileUtils.retrievePermissionFrom(entity.target)?.key]
        map
    }

    def String asString(RolePermission entity){return "com.mogobiz.store.domain.RolePermission : "+entity.id}

}
