// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.json.RenderUtil

/**
 *
 */
class ShippingRuleRender
    extends com.mogobiz.RenderBase<com.mogobiz.store.domain.ShippingRule>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.ShippingRule entity, String lang = 'fr') {
        return RenderUtil.asMapForJSON(["id", "uuid", "countryCode", "minAmount", "maxAmount", "price"], entity)
    }

    def String asString(com.mogobiz.store.domain.ShippingRule entity){return "com.mogobiz.store.domain.ShippingRule : "+entity.id}

}
