// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase;

/**
 *
 */
class StockCalendarRender
    extends RenderBase<StockCalendar>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.StockCalendar entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = [
				'calendarType',
				'remainingStock',
				'remainingStock.stock',
				'remainingStock.stockUnlimited',
				'remainingStock.stockOutSelling',
				'startDate'
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		translate(result, entity, lang)
		return result;
	}

    def String asString(com.mogobiz.store.domain.StockCalendar entity){return "com.mogobiz.store.domain.StockCalendar : "+entity.id}

}
