// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase
import com.mogobiz.service.ProductService;

/**
 *
 */
class SuggestionRender
    extends RenderBase<Suggestion>
{

	ProductService productService
	
    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Suggestion entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = [
				'id',
				'required',
				'position',
				'discount',
				// Product
				'product',
				'product.id',
				'product.code',
				'product.name',
				'product.externalCode',
				'product.state',
				'product.deleted',
				'product.montant',
				'product.text',
				'product.picture',
				'product.video',
				'product.dateCreated',
				'product.modificationDate',
				'product.startDate',
				'product.stopDate',
				// feature
				'product.startFeatureDate',
				'product.stopFeatureDate',
				'product.xtype',
				'product.content',
				'product.url',
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		def resource = entity.product? productService.retrievePicture(entity.product) : null
		if(resource){
			def picture = 
			result['picture'] = resource.asMapForJSON(null, null, lang)
		}
		return result
	}

    def String asString(com.mogobiz.store.domain.Suggestion entity){return "com.mogobiz.store.domain.Suggestion : "+entity.id}

}
