// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.ValidationBase

/**
 *
 */
class TokenValidation
    extends ValidationBase<Token> {

    def beforeInsert(Token entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(Token entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(Token entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(Token entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(Token entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(Token entity) {
        super.afterDelete(entity)
    }

    def onLoad(Token entity) {
        super.onLoad(entity)
    }


}
