// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase
import com.mogobiz.utils.ProfileUtils

/**
 *
 */
class UserPermissionRender extends RenderBase<UserPermission>
{

    Map asMap(List<String> included = [], List<String> excluded = [], UserPermission entity, String lang = 'fr') {
        def map = super.asMap(included && !included.isEmpty() ? included : ['id', 'user', 'user.id', 'target'], excluded, entity, lang)
        map << [key: entity.key ?: ProfileUtils.retrievePermissionFrom(entity.target)?.key]
        map
    }

    def String asString(UserPermission entity){return "com.mogobiz.store.domain.UserPermission : "+entity.id}

}
