// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class VariationRender
    extends RenderBase<Variation>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Variation entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = ['id',
				'name',
				'externalCode',
				'position',
				'hide',
				'uuid'
			]
		}
		Map result = super.asMap(included, excluded, entity, lang);

		List<Map> values = []
		entity.variationValues?.each { value ->
			values.add(value.asMapForJSON())
		}
		result.put ('variationValues', values.sort { a, b -> a.position <=> b.position })
		
		return result;
	}

    def String asString(com.mogobiz.store.domain.Variation entity){return "com.mogobiz.store.domain.Variation : "+entity.id}

}
