// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class VariationValueRender
    extends RenderBase<VariationValue>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.VariationValue entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = ['id', 'value', 'position']
		}
		Map result = super.asMap(included, excluded, entity, lang);
		return result;
	}

    def String asString(com.mogobiz.store.domain.VariationValue entity){return "com.mogobiz.store.domain.VariationValue : "+entity.id}

}
