// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain
/**
 *
 */
class WarehouseStockValidation
    extends com.mogobiz.ValidationBase<com.mogobiz.store.domain.WarehouseStock>
{

    def beforeInsert(com.mogobiz.store.domain.WarehouseStock entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(com.mogobiz.store.domain.WarehouseStock entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(com.mogobiz.store.domain.WarehouseStock entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(com.mogobiz.store.domain.WarehouseStock entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(com.mogobiz.store.domain.WarehouseStock entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(com.mogobiz.store.domain.WarehouseStock entity) {
        super.afterDelete(entity)
    }

    def onLoad(com.mogobiz.store.domain.WarehouseStock entity) {
        super.onLoad(entity)
    }


}
