// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class DatePeriodRender
    extends RenderBase<DatePeriod>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.DatePeriod entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = ['id', 'startDate', 'endDate', 'product', 'product.id', 'pack', 'pack.id']
		}
		Map result = super.asMap(included, excluded, entity, lang);
		return result;
	}

    def String asString(com.mogobiz.store.domain.DatePeriod entity){return "com.mogobiz.store.domain.DatePeriod : "+entity.id}

}
