// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class GoogleCategoryRender
    extends RenderBase<GoogleCategory> {

    Map asMap(List<String> included = [], List<String> excluded = [], GoogleCategory entity, String lang = 'fr') {
        if(!included || included.isEmpty()){
            included = ['id', 'path', 'parentPath', 'lang']
        }
        return super.asMap(included, excluded, entity, lang)
    }

    def String asString(GoogleCategory entity){
        return "com.mogobiz.store.domain.GoogleCategory : "+entity.id
    }

}
