// license-header java merge-point
//
// Generated by: GrailsEntityValidation.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.ValidationBase

/**
 *
 */
class GoogleEnvValidation
    extends ValidationBase<GoogleEnv> {

    def beforeInsert(GoogleEnv entity) {
        super.beforeInsert(entity)
    }

    def beforeUpdate(GoogleEnv entity) {
        super.beforeUpdate(entity)
    }

    def beforeDelete(GoogleEnv entity) {
        super.beforeDelete(entity)
    }

    def afterInsert(GoogleEnv entity) {
        super.afterInsert(entity)
    }

    def afterUpdate(GoogleEnv entity) {
        super.afterUpdate(entity)
    }

    def afterDelete(GoogleEnv entity) {
        super.afterDelete(entity)
    }

    def onLoad(GoogleEnv entity) {
        super.onLoad(entity)
    }


}
