// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase
import com.mogobiz.json.RenderUtil

/**
 *
 */
class IbeaconRender
    extends RenderBase<Ibeacon>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Ibeacon entity, String lang = 'fr') {
        return RenderUtil.asMapForJSON(["id", "uuid", "name", "minor", "major", "startDate", "endDate", "active"], entity)
    }

    def String asString(com.mogobiz.store.domain.Ibeacon entity){return "com.mogobiz.store.domain.Ibeacon : "+entity.id}

}
