// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain
/**
 *
 */
class ProductPropertyRender
    extends com.mogobiz.RenderBase<com.mogobiz.store.domain.ProductProperty>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.ProductProperty entity, String lang = 'fr') {
        return super.asMap(!included || included.size() == 0 ? ['id', 'name', 'value'] : included, excluded, entity, lang)
    }

    def String asString(com.mogobiz.store.domain.ProductProperty entity){return "com.mogobiz.store.domain.ProductProperty : "+entity.id}

}
