// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class ShippingRender
    extends RenderBase<Shipping>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Shipping entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(com.mogobiz.store.domain.Shipping entity){return "com.mogobiz.store.domain.Shipping : "+entity.id}

}
