// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class TagRender
    extends RenderBase<Tag>
{

    java.util.Map asMap(java.util.List<String> included = [], java.util.List<String> excluded = [], com.mogobiz.store.domain.Tag entity, String lang = 'fr') {
		if (included == null || included.size() == 0) {
			included = ["id", "name", "ibeacon", "ibeacon.id", "ibeacon.name"]
		}
		Map result = super.asMap(included, excluded, entity, lang);
		return result;
	}

    def String asString(com.mogobiz.store.domain.Tag entity){return "com.mogobiz.store.domain.Tag : "+entity.id}

}
