// license-header java merge-point
//
// Generated by: GrailsEntityRender.vsl in andromda-grails-cartridge.
//
package com.mogobiz.store.domain

import com.mogobiz.RenderBase

/**
 *
 */
class TokenRender
    extends RenderBase<Token> {

    Map asMap(List<String> included = [], List<String> excluded = [], Token entity, String lang = 'fr') {return super.asMap(included, excluded, entity, lang)}

    def String asString(Token entity){return "com.mogobiz.store.domain.Token : "+entity.id}

}
